apiVersion: v2
description: A Helm chart for my k8s home lab
name: k8s-infra-zyzyx-lab
version: 0.1.0
dependencies:
- name: ingress-nginx
  version: 4.4.2
  repository: https://kubernetes.github.io/ingress-nginx
