apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argo-rollout
  namespace: argocd
spec:
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.22.2
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
