apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |-
        installCRDs: true
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
