apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: falco
  namespace: argocd
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: falco
    helm:
      values: |
        falcosidekick:
          # -- Enable falcosidekick deployment.
          enabled: true
          # -- Enable usage of full FQDN of falcosidekick service (useful when a Proxy is used).
          fullfqdn: true
          webui:
            # -- enable Falcosidekick-UI
            enabled: true
            redis:
              storageSize: "4 Gi"
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 3.0.0

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
