apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana-mimir
  namespace: argocd
spec:
  destination:
    namespace: grafana-mimir
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mimir-distributed
    helm:
      values: |-
        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: minio.zyzyx.virtnet:9001
                  secret_access_key: "grafanaMimir"
                  access_key_id: "LW4jGgN0gJgfvpKHJaMCpijGIgdjNw4x"
                  insecure: true

            blocks_storage:
              s3:
                bucket_name: mimir-blocks

            alertmanager_storage:
              s3:
                bucket_name: mimir-alertmanager

            ruler_storage:
              s3:
                bucket_name: mimir-ruler
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.0.1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
