apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana-mimir
  namespace: argocd
spec:
  destination:
    namespace: grafana-mimir
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mimir-distributed
    helm:
      values: |-
        global:
          # -- Definitions to set up nginx resolver
          dnsService: rke2-coredns-rke2-coredns
          dnsNamespace: kube-system
          clusterDomain: cluster.local
        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: 192.168.1.232:9000
                  secret_access_key: "MOV7Ou6INSSbllgN"
                  access_key_id: "gX6wy0R9WRO9kDAnoeNrGYb9q4d9mMNv"
                  insecure: true

            blocks_storage:
              s3:
                bucket_name: mimir-blocks

            alertmanager_storage:
              s3:
                bucket_name: mimir-alertmanager

            ruler_storage:
              s3:
                bucket_name: mimir-ruler
        minio:
          enabled: false
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.0.1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
