apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: grafana-mimir
  namespace: argocd
spec:
  destination:
    namespace: grafana-mimir
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mimir-distributed
    helm:
      values: |-
        global:
          # -- Definitions to set up nginx resolver
          dnsService: rke2-coredns-rke2-coredns
          dnsNamespace: kube-system
          clusterDomain: cluster.local
          extraEnvFrom:
            - secretRef:
                name: mimir-bucket-secret
          podAnnotations:
            bucketSecretVersion: "0"
        mimir:
          structuredConfig:
            blocks_storage:
              backend: s3
              s3:
                endpoint: minio.zyzyx.virtnet:9000
                bucket_name: mimir-blocks
                access_key_id: ${AWS_ACCESS_KEY_ID}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                insecure: true
            alertmanager_storage:
              backend: s3
              s3:
                endpoint: minio.zyzyx.virtnet:9000
                bucket_name: mimir-am-rule
                access_key_id: ${AWS_ACCESS_KEY_ID}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                insecure: true
            ruler_storage:
              backend: s3
              s3:
                endpoint: minio.zyzyx.virtnet:9000
                bucket_name: mimir-rule
                access_key_id: ${AWS_ACCESS_KEY_ID}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY}
                insecure: true
        minio:
          enabled: false
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.0.1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
